import streamlit as st
from ultralytics import YOLO
from PIL import Image
from datetime import datetime
from fpdf import FPDF
from fpdf.enums import XPos, YPos
import pandas as pd
import io

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Pneumonia CDSS v2.0",
    page_icon="🫁",
    layout="wide"
)

# --- 1. SETUP PDF CLASS ---
class PDFReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 12)
        self.cell(
            0, 10, 'Pneumonia CDSS - Diagnostic Report',
            new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C'
        )
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(
            0, 10, f'Page {self.page_no()}',
            new_x=XPos.RIGHT, new_y=YPos.TOP, align='C'
        )

def create_pdf(img_file, prediction_text, dataframe, timestamp):
    pdf = PDFReport()
    pdf.add_page()

    # Metadata
    pdf.set_font("Helvetica", size=12)
    pdf.cell(200, 10, text=f"Date: {timestamp}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(200, 10, text="Model Version: YOLO26n (v2.0)", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(10)

    # Findings header
    pdf.set_font("Helvetica", 'B', size=14)
    pdf.cell(200, 10, text="Diagnostic Findings:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Findings body
    pdf.set_font("Helvetica", size=12)
    pdf.multi_cell(0, 10, text=prediction_text)

    # Table Data in PDF
    if not dataframe.empty:
        pdf.ln(10)
        pdf.set_font("Helvetica", 'B', size=10)
        pdf.cell(200, 10, text="Detailed Detection Data:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Courier", size=8)

        header = f"{'Class':<15} {'Conf':<10} {'Location (xmin, ymin, xmax, ymax)'}"
        pdf.cell(0, 5, text=header, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(2)

        for _, row in dataframe.iterrows():
            coords = f"{row['xmin']:.1f}, {row['ymin']:.1f}, {row['xmax']:.1f}, {row['ymax']:.1f}"
            line = f"{row['name']:<15} {row['confidence']:.4f}     {coords}"
            pdf.cell(0, 5, text=line, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Disclaimer
    pdf.ln(20)
    pdf.set_font("Helvetica", 'I', size=10)
    pdf.multi_cell(
        0, 10,
        text="DISCLAIMER: This report is generated by an AI Support System (CDSS). "
             "It is NOT a confirmed medical diagnosis."
    )

    return bytes(pdf.output())

# --- 2. LOAD MODEL ---
@st.cache_resource
def load_model():
    return YOLO("yolo26n_v2.pt")

model = load_model()

# --- 3. SIDEBAR ---
st.sidebar.title("⚙️ CDSS Settings Menu")
confidence_threshold = st.sidebar.slider("Sensitivity Threshold", 0.0, 1.0, 0.25, 0.05)
st.sidebar.markdown("---")
st.sidebar.info(
    "**Model Info**\n"
    "- **Arch:** YOLO26 Nano\n"
    "- **Dataset:** 5,000 Balanced Images\n"
    "- **Status:** v2.0 Production"
)

# --- 4. MAIN INTERFACE ---
st.title("🫁 Pneumonia - Clinical Decision Support System v2.0")
st.write("Upload a Chest X-Ray for automated opacity detection and reporting.")

uploaded_file = st.file_uploader("Choose an X-ray...", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    # A. Run Inference
    image = Image.open(uploaded_file)
    results = model.predict(image, conf=confidence_threshold)

    # B. Layout Columns
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Original Scan")
        st.image(image, width='stretch')

    with col2:
        st.subheader("AI Analysis")
        res_plotted = results[0].plot()
        st.image(res_plotted, width='stretch')

    # C. Build Data Table
    boxes = results[0].boxes
    data_list = []

    if len(boxes) > 0:
        for box in boxes:
            x1, y1, x2, y2 = box.xyxy[0].tolist()
            conf = float(box.conf[0])
            cls = int(box.cls[0])
            name = model.names[cls]
            data_list.append({
                "name": name,
                "confidence": round(conf, 4),
                "xmin": round(x1, 2),
                "ymin": round(y1, 2),
                "xmax": round(x2, 2),
                "ymax": round(y2, 2)
            })

    df = pd.DataFrame(data_list)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # D. Analysis Report Section
    st.markdown("---")
    st.subheader("📋 Analysis Report")

    if not df.empty:
        status_msg = f"Detected {len(df)} potential area(s) of Pneumonia."
        report_body = (
            f"The AI system analyzed the uploaded chest X-ray on {timestamp}.\n\n"
            f"FINDINGS:\n"
            f"- The system identified {len(df)} region(s) of interest consistent with pneumonia opacities.\n"
            f"- Highest Confidence Score: {df['confidence'].max()*100:.1f}%\n"
            f"- Average Confidence: {df['confidence'].mean()*100:.1f}%\n\n"
            "IMPRESSION:\n"
            "Findings are suggestive of pneumonia or consolidation. "
            "Please correlate with clinical symptoms and history."
        )
    else:
        status_msg = "No significant opacities detected at current sensitivity."
        report_body = (
            f"The AI system analyzed the uploaded chest X-ray on {timestamp}.\n\n"
            f"FINDINGS:\n"
            f"- No bounding boxes were generated at the sensitivity threshold of {confidence_threshold}.\n\n"
            "IMPRESSION:\n"
            "Unremarkable scan regarding pneumonia opacities based on this model's analysis."
        )

    if not df.empty:
        st.error(status_msg)
    else:
        st.success(status_msg)

    if not df.empty:
        st.dataframe(df, width='stretch')

    st.subheader("📝 Clinical Interpretation")
    st.info(report_body)

    # E. Downloads Section
    st.markdown("---")
    st.subheader("📥 Download")
    d_col1, d_col2 = st.columns(2)

    with d_col1:
        csv = df.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="📄 Download Analysis Data (CSV)",
            data=csv,
            file_name=f"analysis_{datetime.now().strftime('%H%M%S')}.csv",
            mime="text/csv",
            width='stretch'
        )

    with d_col2:
        pdf_bytes = create_pdf(uploaded_file, report_body, df, timestamp)
        st.download_button(
            label="📑 Download Medical Report (PDF)",
            data=pdf_bytes,
            file_name=f"report_{datetime.now().strftime('%H%M%S')}.pdf",
            mime="application/pdf",
            width='stretch'
        )
